version: '3'

services:
  # Production service
  app:
    container_name: dashboard-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"

  # Development service
  app-dev:
    container_name: dashboard-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
